# Generated by Django 5.0.6 on 2024-06-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_chead0_blogpost_chead1_blogpost_chead2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Title',
            new_name='title',
        ),
    ]
