# Generated by Django 5.0.6 on 2024-06-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='msg_id',
            new_name='order_id',
        ),
    ]
